### ISSUE TITLE
Task: Implement YAML storage of aspect values.

### ISSUE THREAD

**Issue by Sharpcastle33** [Sharpcastle33/AspectAlchemy#3]
Complete method stub for getAspects(ItemStack i) in AspectMananger.

The aspects need to be read from a YAML file titled Aspects.yml. I'm not certain if it will be better to load the aspect values into memory or if they should be read from the file on demand. 

getAspects method will need to work for items with different names and lore. We will be using custom items on civex, and an iron ingot named "Adamantine Ingot" will have different aspect values than a normal iron ingot. HiddenOre uses YAML to construct item packages which you can use as an example for how to do this.

The getAspects method will compare an item's material type, name, and lore to see if it matches any item in Aspects.yml. It will then get the appropriate list of aspects and values, and return them as a Map.

HiddenOre's YAML structure looks like this:

```
delirium_ore:

    package:

     - ==: org.bukkit.inventory.ItemStack

       type: PAPER

       amount: 1

       meta:

        ==: ItemMeta

        meta-type: UNSPECIFIC

        display-name: §eDelirium Ore Chunk

        lore:

        - §eTier 1 Resource

        - 

        - §6§oLightweight and cold to the touch.

        - §6§oIt dimly glows a light purple.
```

Aspect.yml's structure should look like this:

```
flamegrassseeds:

    aspects:

    - MUNDANE_FIRE: 3

    - MUNDANE_EARTH: 1

    - MUNDANE_LIFE: 1

    package:

     - ==: org.bukkit.inventory.ItemStack

       type: SEEDS

       meta:

        ==: ItemMeta

        meta-type: UNSPECIFIC

        display-name: §eFlamegrass Seeds

        lore:

        - §eTier 1 Resource

```
